#First Clone from github
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone','https://github.com/pratiksanas5/simple-java-maven-app.git']
      
#Create a mvn Package   
  - name: maven:3.5.0-jdk-8
    entrypoint: 'mvn'
    args: ['clean', 'install', 'package']

  - name: 'gcr.io/cloud-builders/git'
    entrypoint: bash
    args:
    - -c
    - |
      ls -lha
      gsutil -m cp -r target gs://mvn-sample-storage1

